### PR TITLE
Func sig for prometheus/NewProcessCollector() takes a single argument.

### PR DESCRIPTION
**Pull request by mihaller**

### CODE REVIEW

**Comment by ConradWood** [comment]
this does not compile for me:
../../go-easyops/prometheus/registry.go:100:45: not enough arguments in call to prometheus.NewProcessCollector
../../go-easyops/prometheus/registry.go:100:46: undefined: prometheus.ProcessCollectorOpts
can you elaborate please?

**Comment by mihaller** [comment]
It wouldn't compile for me and I noticed that go-easyops/go.mod specifies "github.com/prometheus/client_golang v1.5.1" .  prometheus/NewProcessCollector() takes a ProcessCollectorOpts struct.  

Not sure why we're getting different responses.  Some quirk of vendoring versus modules perhaps?

**Comment by ConradWood** [comment]
probably. I think as-is the patch has to wait until the vendor libraries are updated to a later version and/or it is migrated to using modules.  
There is also a question mark around the replacement of os.GetPid() - does your patch still expose the same metrics as before once it is applied?

**Comment by mihaller** [comment]
Happy for you to reject the pull request (and wait for convert to modules..)

To answer your question about os.GitPid(),  the ProcessCollectorOpts{} decl defaults to {os.Getpid(), ""}.

**Comment by ConradWood** [comment]
moving to modules instead of vendoring IMHO is desirable, even necessary. It does need some form of goproxy though, to be safe. so, I'll keep this patch around, until we goproxy is complete enough, then we move to modules and then update it and then merge it, ok?

**Comment by mihaller** [comment]
Yep.  Happy to help with the migrate to modules when you're ready.  Let me know.

**Comment by ConradWood** [comment]
I made some progress with the support for modules. Essentially 
go get golang.conradwood.net/go-easyops now seems to work 
This in turn meant, I can fully remove the vendor folder,
this in turn meant, that the dependencies and be resolved and upgraded
and that meant, your patch works for me too now.
It's integrated now.
Thanks!

**Comment by mihaller** [comment]
Sounds good.  Thanks.  I'll see if I can delete the pull requests as it isn't needed.  Look forward to learning more about go-easyops.

**Pull request closed without merging**
